# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a41631d627c6d2c0151d085222983407008d4af2f5518636d03e223edd86f0f5e47c04d7dfeafd8c9b8a83f27ca7839e40583932bf35312fe55b3eae29f1134

test:
  secret_key_base: 9212ba41d76b629e4dfe5571aa0b5d1ba8a068ef02f52280276d085e35b95aa5b277dc3a54770f89fbe7d45763b9112b6d566f15b4aa7cf169dd0e81e1368f12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
